# Generated by Django 5.0.6 on 2024-07-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatbot", "0003_chatbot_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="session_id",
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
