# Generated by Django 5.0.6 on 2024-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatbot", "0004_alter_chatbot_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="session_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
