# Generated by Django 5.0.6 on 2024-07-12 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("soil", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chatbot",
            new_name="crop_data",
        ),
    ]
