# Generated by Django 5.0.6 on 2024-07-15 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soil", "0003_crop_data_detailed_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop_data",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
