# Generated by Django 5.0.6 on 2024-07-13 06:53

import aivle_big.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=aivle_big.storage_backends.PestDetectionStorage(),
                upload_to="post/",
            ),
        ),
    ]
