# Generated by Django 5.0.6 on 2024-07-09 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pest_name", models.CharField(max_length=100)),
                ("occurrence_environment", models.TextField(blank=True, null=True)),
                ("symptom_description", models.TextField(blank=True, null=True)),
                ("prevention_methods", models.TextField(blank=True, null=True)),
                (
                    "pesticide_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PestDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pest_detections/"
                    ),
                ),
                ("detection_date", models.DateTimeField(auto_now_add=True)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="detect.pest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
