# Generated by Django 5.0.6 on 2024-07-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pestdetection",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
