# Generated by Django 5.0.6 on 2024-07-13 06:32

import aivle_big.storage_backends
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0002_alter_pestdetection_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pestdetection",
            name="detection_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pestdetection",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=aivle_big.storage_backends.PestDetectionStorage(),
                upload_to="pest_detections/",
            ),
        ),
    ]
